knp_doctrine_behaviors:
  blameable:       false
  geocodable:      false
  loggable:        false
  sluggable:       false
  soft_deletable:  true
  translatable:    false
  timestampable:   true
  sortable:        true